import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index':                    'src/index.ts',
    'atoms/Button':             'src/atoms/Button.tsx',
    'atoms/Input':              'src/atoms/Input.tsx',
    'atoms/Badge':              'src/atoms/Badge.tsx',
    'atoms/Label':              'src/atoms/Label.tsx',
    'atoms/Skeleton':           'src/atoms/Skeleton.tsx',
    'atoms/Textarea':           'src/atoms/Textarea.tsx',
    'atoms/Switch':             'src/atoms/Switch.tsx',
    'atoms/Checkbox':           'src/atoms/Checkbox.tsx',
    'atoms/Progress':           'src/atoms/Progress.tsx',
    'atoms/Select':             'src/atoms/Select.tsx',
    'molecules/Card':           'src/molecules/Card.tsx',
    'molecules/Alert':          'src/molecules/Alert.tsx',
    'molecules/Tabs':           'src/molecules/Tabs.tsx',
    'molecules/Dialog':         'src/molecules/Dialog.tsx',
    'molecules/Tooltip':        'src/molecules/Tooltip.tsx',
    'molecules/Separator':      'src/molecules/Separator.tsx',
    'molecules/Table':          'src/molecules/Table.tsx',
    'molecules/AlertDialog':    'src/molecules/AlertDialog.tsx',
  },
  format: ['esm'],
  dts: true,
  external: ['react', 'react-dom', '@vientonorte/a11y'],
  splitting: false,
  clean: true,
  jsx: 'react-jsx',
});
